### ISSUE TITLE
Mixed messages

### ISSUE THREAD

**Issue by navtemmt** [tapnisu/forwarding-discord-telegram#100]
Hello its me again haha, another issue another thread, sometimes when two messages in discord is posted almost at the same time the bot forward the two message together in one messages (separated with a blank line), for example:

[02/02/23, 08:23:43 AM] [FX SING / FOREX#0000]: <@&1034352912165523497>
  Description: 
        AUDNZD SELL 1.09830
SL 1.10021
  Url: 1675326223024

[02/02/23, 08:23:43 AM][Yeecord / ┣💰┃簽到 / 血珀#7541]: .

I wonder if it is possible to disable this function and make the bot always forward 1 message from discord at a time, would love to have this function if possible, thanks in regards !

**Comment by tapnisu** [comment]
Hello again! Thanks for your another issue!

Originally it was a feature, not a bug :D

When there is a lot of messages, telegram won't let to send all of them (so, I am sending all messages together)

![image](https://user-images.githubusercontent.com/57483029/216773869-30315cae-bb48-496a-aaf0-1020847acc41.png)

I will add option to disable it

**Comment by navtemmt** [comment]
I see I see, it was a nice feature to ensure all messages are forward to telegram.. Just my personal preference to have it one by one if possible, thank you for the hardwork ! :D

**Comment by tapnisu** [comment]
Oh hi!
I added option to disable / enable message stacking.
It is enabled by default

**Comment by navtemmt** [comment]
Cool, thanks man ! Love it !
Just pulled the updates to my server, it should be working fine, have a good night!
