### ISSUE TITLE
Forwarding messages from all channels 

### ISSUE THREAD

**Issue by papix69** [tapnisu/forwarding-discord-telegram#154]
I only added a single channel id in allowedchannelids but still it's forwarding messages from all the channels

**Comment by tapnisu** [comment]
Oh, hello! Can you show your `config.json`, so I can see what is wrong?

**Comment by papix69** [comment]
![image](https://github.com/tapnisu/forwarding-discord-telegram/assets/84144555/2d1928f6-2008-4c74-a20d-18c50d192b49)

i even tried removing channel Configs and kept only muted channel and allowed channel but still it's forwarding messages from all channels.

**Comment by tapnisu** [comment]
Are you sure you are editing `config.json`, not the `example.config.json`?

**Comment by papix69** [comment]
Yes bro 100% lol

**Comment by tapnisu** [comment]
Try using this config:

```json
{
	"mutedChannelsIds": [],
	"allowedChannelsIds": [1135667594960056614],
	"allowedUsersIds": [],
	"mutedUsersIds": [],
	"channelConfigs": {
		"1141985479521226814": {
			"muted": [],
			"allowed": [1141985479521226814]
		}
	},
	"showDate": false,
	"showChat": true,
	"stackMessages": false
}
```

Actually, I still have no idea how this is not working

**Comment by papix69** [comment]
Are you sure if I do this it'll not spam the telegram channel
? Because last time I did that it spammed my channel 
With links and vulgar messages

**Comment by papix69** [comment]
Can I have your discord?

**Comment by tapnisu** [comment]
My discord is `tapnisu`

**Comment by tapnisu** [comment]
> Are you sure if I do this it'll not spam the telegram channel ? Because last time I did that it spammed my channel With links and vulgar messages.
> 
> Can I have your discord?

Can you invite me to server you are testing this on? It works perfectly on my machine

**Comment by papix69** [comment]
Ok thank you!!
